server:
  port: 8888

spring:
  profiles:
    include:
      - db
      - slack
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug